### ISSUE TITLE
No matching distribution found for requirements.txt

### ISSUE THREAD

**Issue by sashasaturn** [maxfyk/mail_stats#1]
pip3 install requirements.txt 
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt

**Comment by maxfyk** [comment]
@sashasaturn 
The <a herd="https://stackoverflow.com/questions/42876592/unable-to-install-using-pip-install-requirements-txt">correct command</a> would be:
`pip3 install -r requirements.txt`.

**Comment by maxfyk** [comment]
@sashasaturn 
Please, let me know if I solved your issue, so I could close it.
